### ISSUE TITLE
import discretisedfield error

### ISSUE THREAD

**Issue by zkhodzhaev** [ubermag/help#225]
I am running in a supercomputer node, I am getting this error:

_c302-005.ls6(1017)$ python 3.correlation_auto.py 
Traceback (most recent call last):
  File "/scratch/08895/bobojon/mumax3/137.reference_short_paramStabilityTest_Ku0p7412e6_pol0p6_14ns_900ns.mx3-general-mumax3.sl-20-24_Tuesday_September_27_2022/3.correlation_auto.py", line 3, in <module>
    import discretisedfield as df
  File "/home1/08895/bobojon/.local/lib/python3.9/site-packages/discretisedfield/__init__.py", line 8, in <module>
    from .field import Field
  File "/home1/08895/bobojon/.local/lib/python3.9/site-packages/discretisedfield/field.py", line 9, in <module>
    import h5py
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/site-packages/h5py/__init__.py", line 25, in <module>
    from . import _errors
ImportError: /opt/apps/intel19/python3/3.9.7/lib/python3.9/site-packages/h5py/_errors.cpython-39-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned_

**Comment by lang-m** [comment]
Hi @zkhodzhaev this looks like a problem with `h5py` on the supercomputer (maybe a mixture of different compilers?). I suggest that you get in touch with the local supercomputer support.
