### ISSUE TITLE
Issue with oommf - compile from source on M1/M2

### ISSUE THREAD

**Issue by MiroCaf** [ubermag/help#270]
Hello,

I am working on a MacOs. I have installed anaconda and python 3.10.  I followed the instructions which suggested to install Ubermag using conda, but I get the error below. 

<img width="980" alt="Schermata 2023-12-27 alle 09 00 14" src="https://github.com/ubermag/help/assets/154966035/6e6759d5-b701-4fca-810d-63fd188461f8">

I thus used pip and everything seemed ok in the terminal. However when running the first simulation, I get the error below

<img width="1384" alt="Schermata 2023-12-27 alle 09 16 16" src="https://github.com/ubermag/help/assets/154966035/58c0daa7-9bb2-48ac-b73f-c8a5ab8c5cfe">

Any help would be greatly appreciated.

Thanks,

Miro

**Comment by fangohr** [comment]
I am guessing you may have a M1/M2/M3 processor? If so, then the problem is that there is no conda package for OOMMF for the M1/M2/M3 architecture at the moment.

Try to follow the instructions in the `MacOS` tab at https://ubermag.github.io/installation.html#advanced-installation . I think this should work.

**Comment by MiroCaf** [comment]
Hello, and thanks for your reply and for your help. As I mentioned above, I firstly tried conda and then  the advanced installation using pip, but still I get the error "cannot find OOMMF".  Any help would be greatly appreciated

**Comment by fangohr** [comment]
Did you compile OOMMF?

**Comment by MiroCaf** [comment]
yep, I typed cd oommf and then make build

**Comment by MiroCaf** [comment]
<img width="1278" alt="Schermata 2024-01-06 alle 17 14 14" src="https://github.com/ubermag/help/assets/154966035/77000b43-f6f7-47b7-8fc8-ef5bd63b533e">

**Comment by MiroCaf** [comment]
I have just compiled once again as per attachment above. It seems to be compiling okay but it keeps on returning the same error:

<img width="1392" alt="Schermata 2024-01-06 alle 17 17 07" src="https://github.com/ubermag/help/assets/154966035/291bbdee-9081-4dac-89da-0826262d9983">

**Comment by fangohr** [comment]
The compilation of OOMMF looks fine.

By the way, you can copy and paste code into these issues (rather than posting screenshots). That's generally better as there is less data to move, and we can search the charactors you post. This is explained [here for example](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

≈

**Comment by MiroCaf** [comment]
Ok, sorry for that- I will copy and paste code from now onwards. 

Any suggestions by the way on what to do with the error? Thanks again

**Comment by fangohr** [comment]
Did you do anything to export the `OOMMFTCL` variable? (Step 6 in the instructions). 

[This is a good occasion to check the instructions work for you and are correct.]

Could you (in a Terminal App window) run the command 
```console
python3 -c "import oommfc; oommfc.runner.runner.status"
```
from https://ubermag.github.io/installation.html#check-the-installation and post the command and output, please.

**Comment by fangohr** [comment]
Also a 
```console
echo $OOMMFTCL
``` 
would be interesting to run in the same shell (i.e. in the Terminal App window).

**Comment by MiroCaf** [comment]
mirocafolla@192 oommf % export OOMMFTCL="/Users/mirocafolla/oommf/oommf.tcl"     

this is what I did after make build

**Comment by MiroCaf** [comment]
(base) mirocafolla@192 oommf % python3 -c "import oommfc; oommfc.runner.runner.status"                                           
OOMMFTCL is set, but OOMMF could not be run.
stdout:
b''
stderr:
b'couldn\'t read file "/Users/mirocafolla/anaconda3/lib/python3.10/site-packages/oommf/oommf.tcl": no such file or directory\n'
Docker was not found.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mirocafolla/anaconda3/lib/python3.10/site-packages/oommfc/oommf/oommf.py", line 435, in runner
    self.autoselect_runner()
  File "/Users/mirocafolla/anaconda3/lib/python3.10/site-packages/oommfc/oommf/oommf.py", line 572, in autoselect_runner
    raise EnvironmentError("Cannot find OOMMF.")
OSError: Cannot find OOMMF.

**Comment by MiroCaf** [comment]
(base) mirocafolla@192 oommf % echo $OOMMFTCL
/Users/mirocafolla/anaconda3/lib/python3.10/site-packages/oommf/oommf.tcl

**Comment by MiroCaf** [comment]
I think that it says 
/Users/mirocafolla/anaconda3/lib/python3.10/site-packages/oommf/oommf.tcl

because I have tried to export OOMMF into different directories. Firstly into /Users/mirocafolla/oommf, and then into /Users/mirocafolla/anaconda3/lib/python3.10/site-packages/oommf/oommf.tcl as the former was not working. Neither works though

**Comment by fangohr** [comment]
Please use 
````
```console
fangohr@MBAM2 docker % echo "Hello world"
Hello world
```
````

to make your code snippets look nicer. You can use the "Preview" tab to check.

This should look like

```console
fangohr@MBAM2 docker % echo "Hello world"
Hello world
```

**Comment by MiroCaf** [comment]
(base) mirocafolla@192 oommf % echo "Hello world"
Hello world

**Comment by fangohr** [comment]
The OOMMFTCL variable needs to point to the `oommf.tcl` file from the place where you have compiled OOMMF. Based on your screenshots, I guess this would be

```console
export OOMMFTCL="/Users/mirocafolla/oommf/oommf.tcl"
```
Once you have done that, please run 
```console
echo $OOMMFTCL
``` 
so we can double check this has worked. Then please run 

```console
ls -l $OOMMFTCL
``` 

and finally 
```console
python3 -c "import oommfc; oommfc.runner.runner.status"
```
and copy and paste the commands and outputs here (all together in one code block is fine).

**Comment by MiroCaf** [comment]
(base) mirocafolla@192 oommf % export OOMMFTCL="/Users/mirocafolla/oommf/oommf.tcl"
(base) mirocafolla@192 oommf % echo $OOMMFTCL
/Users/mirocafolla/oommf/oommf.tcl
(base) mirocafolla@192 oommf % ls -l $OOMMFTCL
ls: /Users/mirocafolla/oommf/oommf.tcl: No such file or directory
(base) mirocafolla@192 oommf % python3 -c "import oommfc; oommfc.runner.runner.status"
OOMMFTCL is set, but OOMMF could not be run.
stdout:
b''
stderr:
b'couldn\'t read file "/Users/mirocafolla/oommf/oommf.tcl": no such file or directory\n'
Docker was not found.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mirocafolla/anaconda3/lib/python3.10/site-packages/oommfc/oommf/oommf.py", line 435, in runner
    self.autoselect_runner()
  File "/Users/mirocafolla/anaconda3/lib/python3.10/site-packages/oommfc/oommf/oommf.py", line 572, in autoselect_runner
    raise EnvironmentError("Cannot find OOMMF.")
OSError: Cannot find OOMMF.

**Comment by fangohr** [comment]
```console
base) mirocafolla@192 oommf % ls -l $OOMMFTCL
ls: /Users/mirocafolla/oommf/oommf.tcl: No such file or directory
```
this means that the file (`oommf.tcl`) is not in that location. You need to find it, and point `OOMMFTCL` to it. 

Perhaps it is `/Users/mirocafolla/oommf/oommf/oommf.tcl` instead?

**Comment by fangohr** [comment]
> (base) mirocafolla@192 oommf % echo "Hello world" Hello world

Thanks for running that. In particular, I was hoping for this formatting of your output:
```console
(base) mirocafolla@192 oommf % echo "Hello world"
Hello world
```

**Comment by MiroCaf** [comment]
Good morning, and thank you very much for all your help with this. I tried this and I think that we are getting there! :)

(base) mirocafolla@192 oommf % export OOMMFTCL="/Users/mirocafolla/oommf/oommf/oommf.tcl"
(base) mirocafolla@192 oommf % echo $oommftcl

(base) mirocafolla@192 oommf % ls -l $OOMMFTCL
-rwxr-xr-x  1 mirocafolla  staff  14625 26 Dic 18:43 /Users/mirocafolla/oommf/oommf/oommf.tcl
(base) mirocafolla@192 oommf % python3 -c "import oommfc; oommfc.runner.runner.status"
Running OOMMF (TclOOMMFRunner)[2024/01/07 10:03]... (2.4 s)
OOMMF found and running.
(base) mirocafolla@192 oommf %

**Comment by MiroCaf** [comment]
However, when I run it in the console it keeps on returning the same error 

runfile('/Users/mirocafolla/.spyder-py3/temp.py', wdir='/Users/mirocafolla/.spyder-py3')
Docker was not found.
Traceback (most recent call last):

  File ~/anaconda3/lib/python3.10/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/.spyder-py3/temp.py:22
    oommfc.runner.autoselect_runner()

  File ~/anaconda3/lib/python3.10/site-packages/oommfc/oommf/oommf.py:572 in autoselect_runner
    raise EnvironmentError("Cannot find OOMMF.")

OSError: Cannot find OOMMF.

I tried close and relaunch, but still the same error :(

**Comment by MiroCaf** [comment]
My bad. I think that it is now working. I slightly modified my Python code adding some extra lines with respect to the demo and it is seems okay

[import numpy
import ubermag
import oommfc 
import pandas as pd

oommfc.runner
oommfc.runner.envvar
import micromagneticmodel as mm  # mm is just a shorter name we want to use later
import discretisedfield as df  # df is just a shorter name we want to use later


oommfc.runner.oommf_exe
oommfc.runner.docker_exe
# oommfc.runner.autoselect_runner()
oommfc.runner.runner = oommfc.oommf.TclOOMMFRunner("/Users/mirocafolla/oommf/oommf/oommf.tcl")
print (oommfc.runner)
# oommfc.runner.autoselect_runner()
import matplotlib.pyplot as plt
oommfc.runner.runner.status
pd.options.display.max_rows = 5
pd.options.display.float_format = '{:,.2e}'.format


system = mm.System(name='first_ubermag_simulation')

A = 1e-12  # exchange energy constant (J/m)
H = (5e6, 0, 0)  # external magnetic field in the x-direction (A/m)
system.energy = mm.Exchange(A=A) + mm.Demag() + mm.Zeeman(H=H)

L = 50e-9  # cubic sample edge length (m)
region = df.Region(p1=(0, 0, 0), p2=(L, L, L))
mesh = df.Mesh(region=region, n=(10, 10, 10))

Ms = 8e6  # saturation magnetisation (A/m)
system.m = df.Field(mesh, nvdim=3, value=(0, 1, 0), norm=Ms)

print (system.energy)
system.energy
system.m.mesh.region.mpl()
system.m.mesh.mpl()
system.m.sel('z').mpl()

print(f'{ubermag.__version__=}, {oommfc.__version__=}')
 
md = oommfc.MinDriver()
md.drive(system)](url)

**Comment by MiroCaf** [comment]
My bad. I think that it is now working. I slightly modified my Python code adding some extra lines with respect to the demo and it is seems okay

import numpy
import ubermag
import oommfc 
import pandas as pd

oommfc.runner
oommfc.runner.envvar
import micromagneticmodel as mm  # mm is just a shorter name we want to use later
import discretisedfield as df  # df is just a shorter name we want to use later
oommfc.runner.oommf_exe
oommfc.runner.docker_exe

oommfc.runner.runner = oommfc.oommf.TclOOMMFRunner("/Users/mirocafolla/oommf/oommf/oommf.tcl")
print (oommfc.runner)

import matplotlib.pyplot as plt
oommfc.runner.runner.status
pd.options.display.max_rows = 5
pd.options.display.float_format = '{:,.2e}'.format


system = mm.System(name='first_ubermag_simulation')

A = 1e-12  # exchange energy constant (J/m)
H = (5e6, 0, 0)  # external magnetic field in the x-direction (A/m)
system.energy = mm.Exchange(A=A) + mm.Demag() + mm.Zeeman(H=H)

L = 50e-9  # cubic sample edge length (m)
region = df.Region(p1=(0, 0, 0), p2=(L, L, L))
mesh = df.Mesh(region=region, n=(10, 10, 10))

Ms = 8e6  # saturation magnetisation (A/m)
system.m = df.Field(mesh, nvdim=3, value=(0, 1, 0), norm=Ms)

print (system.energy)
system.energy
system.m.mesh.region.mpl()
system.m.mesh.mpl()
system.m.sel('z').mpl()

print(f'{ubermag.__version__=}, {oommfc.__version__=}')
 
md = oommfc.MinDriver()
md.drive(system)

**Comment by MiroCaf** [comment]
and this is the output

runfile('/Users/mirocafolla/.spyder-py3/temp.py', wdir='/Users/mirocafolla/.spyder-py3')
Running OOMMF (TclOOMMFRunner)[2024/01/07 10:10]... (2.1 s)
OOMMF found and running.
OOMMF runner: TclOOMMFRunner(/Users/mirocafolla/oommf/oommf/oommf.tcl)
runner is cached: True
Running OOMMF (TclOOMMFRunner)[2024/01/07 10:10]... (1.1 s)
OOMMF found and running.
Exchange(A=1e-12) + Demag() + Zeeman(H=(5000000.0, 0, 0))
ubermag.__version__='2023.11', oommfc.__version__='0.64.1'
Running OOMMF (TclOOMMFRunner)[2024/01/07 10:10]... (1.1 s)

**Comment by MiroCaf** [comment]
Once again, thank you so much for all your help. I will now get through the other demo examples, and will then simulate my own system. Hopefully, I will not be bothering you again! :)

**Comment by fangohr** [comment]
```console
(base) mirocafolla@192 oommf % ls -l $OOMMFTCL
 -rwxr-xr-x 1 mirocafolla staff 14625 26 Dic 18:43 /Users/mirocafolla/oommf/oommf/oommf.tcl 
(base) mirocafolla@192 oommf % python3 -c "import oommfc; oommfc.runner.runner.status" 
Running OOMMF (TclOOMMFRunner)[2024/01/07 10:03]... (2.4 s) 
OOMMF found and running. 
(base) mirocafolla@192 oommf %
```
just to confirm that this is the output we are hoping for. So the OOMMFTCL variable is correct then, and Ubermag can find and execute OOMMF at that location. At least if you call Python from that command line (where the OOMMFTCL environment variable is defined).

**Comment by fangohr** [comment]
> However, when I run it in the console it keeps on returning the same error
> 
> runfile('/Users/mirocafolla/.spyder-py3/temp.py', wdir='/Users/mirocafolla/.spyder-py3') 

So here you are running inside Spyder. This Python instance presumably doesn't know about the OOMMFTCL variable; perhaps because you started Spyder in a different shell or before you defined the OOMMFTCL variable.

One thing you can try to to set the variable as before (`export OOMMFTCL="/Users/mirocafolla/oommf/oommf/oommf.tcl"`) and then start spyder. 

Does it work then?

**Comment by fangohr** [comment]
Setting the path directly from Python (`oommfc.runner.runner = oommfc.oommf.TclOOMMFRunner("/Users/mirocafolla/oommf/oommf/oommf.tcl"`) is okay: it should work reliably on this computer where you have OOMMF installed in that location. If you want to run the same script on a different machine, you would need to update that line.

**Comment by MiroCaf** [comment]
Thanks!

**Comment by MiroCaf** [comment]
So sorry to bother you again, but I was trying to run it on another machine. I have followed the advanced installation and replicated the steps above (changing the directory when needed) but Spyder cannot import Ubermag and oomph

/runfile('/Users/clodomirocafolla/Desktop/untitled0.py', wdir='/Users/clodomirocafolla/Desktop')
Traceback (most recent call last):

  File "/Users/clodomirocafolla/Desktop/untitled0.py", line 10, in <module>
    import ubermag



ModuleNotFoundError: No module named 'ubermag'

runfile('/Users/clodomirocafolla/Desktop/untitled0.py', wdir='/Users/clodomirocafolla/Desktop')
Traceback (most recent call last):

  File "/Users/clodomirocafolla/Desktop/untitled0.py", line 11, in <module>
    import oommfc

ModuleNotFoundError: No module named 'oommfc'

**Comment by MiroCaf** [comment]
I had compiled OOMMF and checked it. It seemed fine 

lib -o darwin/ddtest
---------------------------------------
---  Testing Xp_DoubleDouble build  ---
darwin/ddtest basetest
All 94 tests passed.
--- Xp_DoubleDouble build looks OK. ---
---------------------------------------
<84354> pimake 2.0a3  info:
Target '' up to date.
Built Sun Jan 07 12:06:14 CET 2024
Current time: Sun Jan 07 12:06:14 CET 2024
(base) 192:oommf clodomirocafolla$ export OOMMFTCL="/Users/clodomirocafolla/oommf/oommf/oommf.tcl"
(base) 192:oommf clodomirocafolla$ echo $OOMMFTCL
/Users/clodomirocafolla/oommf/oommf/oommf.tcl
(base) 192:oommf clodomirocafolla$ ls -l $OOMMFTCL
-rwxr-xr-x  1 clodomirocafolla  staff  11434 22 May  2022 /Users/clodomirocafolla/oommf/oommf/oommf.tcl
(base) 192:oommf clodomirocafolla$ python3 -c "import oommfc; oommfc.runner.runner.status"
Running OOMMF (TclOOMMFRunner)[2024/01/07 12:07]... (2.8 s)
OOMMF found and running.
(base) 192:oommf clodomirocafolla$

**Comment by MiroCaf** [comment]
I had compiled OOMMF and checked it. It seemed fine

/---  Testing Xp_DoubleDouble build  ---
darwin/ddtest basetest
All 94 tests passed.
--- Xp_DoubleDouble build looks OK. ---
---------------------------------------
<84354> pimake 2.0a3  info:
Target '' up to date.
Built Sun Jan 07 12:06:14 CET 2024
Current time: Sun Jan 07 12:06:14 CET 2024
(base) 192:oommf clodomirocafolla$ export OOMMFTCL="/Users/clodomirocafolla/oommf/oommf/oommf.tcl"
(base) 192:oommf clodomirocafolla$ echo $OOMMFTCL
/Users/clodomirocafolla/oommf/oommf/oommf.tcl
(base) 192:oommf clodomirocafolla$ ls -l $OOMMFTCL
-rwxr-xr-x  1 clodomirocafolla  staff  11434 22 May  2022 /Users/clodomirocafolla/oommf/oommf/oommf.tcl
(base) 192:oommf clodomirocafolla$ python3 -c "import oommfc; oommfc.runner.runner.status"
Running OOMMF (TclOOMMFRunner)[2024/01/07 12:07]... (2.8 s)
OOMMF found and running.
(base) 192:oommf clodomirocafolla$

**Comment by MiroCaf** [comment]
However, there seems to be issues with Ubermag. I run python -c "import ubermag; ubermag.test()" and got

===== 98 failed, 3815 passed, 2 skipped, 125 warnings in 421.51s (0:07:01) =====
Account lookup failure: clodomirocafolla
Account lookup failure: clodomirocafolla
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/clodomirocafolla/miniconda3/lib/python3.8/site-packages/oommfc/oommf/oommf.py", line 27, in _global_cleanup
    instance._terminate()
  File "/Users/clodomirocafolla/miniconda3/lib/python3.8/site-packages/oommfc/oommf/oommf.py", line 52, in _terminate
    self._kill()
  File "/Users/clodomirocafolla/miniconda3/lib/python3.8/site-packages/oommfc/oommf/oommf.py", line 231, in _kill
    sp.run(command, env=self.env)
AttributeError: 'ExeOOMMFRunner' object has no attribute 'env'

**Comment by fangohr** [comment]
This is a different problem. Please open a new issue.

**Comment by fangohr** [comment]
> > However, when I run it in the console it keeps on returning the same error
> > runfile('/Users/mirocafolla/.spyder-py3/temp.py', wdir='/Users/mirocafolla/.spyder-py3')
> 
> So here you are running inside Spyder. This Python instance presumably doesn't know about the OOMMFTCL variable; perhaps because you started Spyder in a different shell or before you defined the OOMMFTCL variable.
> 
> One thing you can try to to set the variable as before (`export OOMMFTCL="/Users/mirocafolla/oommf/oommf/oommf.tcl"`) and then start spyder.
> 
> Does it work then?

@MiroCaf - can you please try what I suggested above? (It might be useful info to fix your next problem.)

Also, in your home directory, you probably have a file call `.profile`. Try to list it with this command.
```console
ls -l -a ~/.profile
```
If it exists, then open it in a text editor (you can use Spyder), and add a line at the end containing `export OOMMFTCL="/Users/mirocafolla/oommf/oommf/oommf.tcl"`. Then open a new shell, and see if OOMMFTCL is defined, and if the Ubermag runner tests succeeds. This should work, and should be a better solution than always repeating the `export OOMMFTCL="/Users/mirocafolla/oommf/oommf/oommf.tcl"` at the shell, and also better than having this line `oommfc.runner.runner = oommfc.oommf.TclOOMMFRunner("/Users/mirocafolla/oommf/oommf/oommf.tcl")` in all your simulation files.

**Comment by MiroCaf** [comment]
Thanks again. Shall I open a new issue anyway with the other problem?

**Comment by MiroCaf** [comment]
I tried to do what you were suggesting. Maybe I am doing something wrong but this is what I get

(base) mirocafolla@192 ~ % ls -l -a ~/.profile
ls: /Users/mirocafolla/.profile: No such file or directory
(base) mirocafolla@192 ~ % cd ..
(base) mirocafolla@192 /Users % pwd
/Users
(base) mirocafolla@192 /Users % ls -l -a ~/.profile
ls: /Users/mirocafolla/.profile: No such file or directory
(base) mirocafolla@192 /Users % cd ..
(base) mirocafolla@192 / % ls -l -a ~/.profile
ls: /Users/mirocafolla/.profile: No such file or directory
(base) mirocafolla@192 / %

**Comment by fangohr** [comment]
That's interesting, thank you.

Could you run a `ls -l -a ~/` and paste the output here? (Feel free to remove your own/confidential filenames - I am only interested in the ones starting with a `.`) Thanks.

**Comment by MiroCaf** [comment]
```console
ls: /Users/mirocafolla/.profile: No such file or directory
(base) mirocafolla@192 / % ls -l -a ~/
total 832
drwxr-xr-x+ 41 mirocafolla  staff    1312  6 Gen 21:15 .
drwxr-xr-x   5 root         admin     160  4 Apr  2020 ..
-rw-r--r--@  1 mirocafolla  staff   14340 31 Dic 10:53 .DS_Store
drwx------@  2 mirocafolla  staff      64  6 Gen 19:18 .Trash
drwxr-xr-x   4 mirocafolla  staff     128 26 Dic 20:21 .anaconda
-rw-------   1 mirocafolla  staff     539 27 Dic 08:56 .bash_history
-rw-r--r--   1 mirocafolla  staff     503  8 Apr  2023 .bash_profile
drwxr-xr-x   4 mirocafolla  staff     128  7 Gen 19:39 .conda
-rw-r--r--   1 mirocafolla  staff      49 29 Dic 15:26 .condarc
drwxr-xr-x   4 mirocafolla  staff     128 17 Apr  2023 .config
drwxr-xr-x   3 mirocafolla  staff      96 11 Apr  2023 .continuum
drwxr-xr-x   3 mirocafolla  staff      96 27 Dic 09:48 .ipynb_checkpoints
drwxr-xr-x   3 mirocafolla  staff      96 11 Apr  2023 .ipython
drwxr-xr-x   4 mirocafolla  staff     128 27 Dic 09:48 .jupyter
drwxr-xr-x   3 mirocafolla  staff      96 11 Apr  2023 .matplotlib
drwxr-xr-x   6 mirocafolla  staff     192 29 Dic 19:12 .pytest_cache
drwxr-xr-x  19 mirocafolla  staff     608  7 Gen 13:04 .spyder-py3
-rw-r--r--   1 mirocafolla  staff     323  8 Apr  2023 .tcshrc
drwxr-xr-x   3 mirocafolla  staff      96 30 Dic 09:25 .virtual_documents
drwx------   4 mirocafolla  staff     128 27 Set  2020 .vnc
-rw-r--r--   1 mirocafolla  staff     691  8 Apr  2023 .xonshrc
-rw-r--r--   1 mirocafolla  staff     243 23 Dic 19:14 .zprofile
-rw-------   1 mirocafolla  staff    8706  6 Gen 16:45 .zsh_history
-rw-r--r--   1 mirocafolla  staff     502  8 Apr  2023 .zshrc
```

**Comment by fangohr** [comment]
Okay, thanks. I'd  like to know if you are using bash or zsh. Please enter 
```console 
echo $SHELL
```
and post the output.

**Comment by fangohr** [comment]
Can you also edit your `~/.bash_profile` (you can use Spyder), and add a line at the end containing `export OOMMFTCL="/Users/mirocafolla/oommf/oommf/oommf.tcl"`. Then open a new shell, and see if OOMMFTCL is defined (i.e. `echo $OOMMFTCL`), and if the Ubermag runner tests succeed.

**Comment by MiroCaf** [comment]
Good morning and thank you very much once again for all your help :)
I think I am using zsh
(base) mirocafolla@192 / % echo $SHELL
/bin/zsh
(base) mirocafolla@192 / %

**Comment by MiroCaf** [comment]
(base) mirocafolla@192 / % ~/.bash_profile
zsh: permission denied: /Users/mirocafolla/.bash_profile
(base) mirocafolla@192 / % export OOMMFTCL="/Users/mirocafolla/.bash_profile/oommf/oommf/oommf.tcl"

**Comment by MiroCaf** [comment]
(base) mirocafolla@192 / % python -c "import ubermag; ubermag.test()"

......
========================== 114 failed, 3799 passed, 2 skipped, 673 warnings in 322.82s (0:05:22) ===========================
couldn't read file "/Users/mirocafolla/.bash_profile/oommf/oommf/oommf.tcl": not a directory
Exception ignored in atexit callback: <function _global_cleanup at 0x7fdbb0612cb0>
Traceback (most recent call last):
  File "/Users/mirocafolla/anaconda3/lib/python3.10/site-packages/oommfc/oommf/oommf.py", line 27, in _global_cleanup
    instance._terminate()
  File "/Users/mirocafolla/anaconda3/lib/python3.10/site-packages/oommfc/oommf/oommf.py", line 52, in _terminate
    self._kill()
  File "/Users/mirocafolla/anaconda3/lib/python3.10/site-packages/oommfc/oommf/oommf.py", line 231, in _kill
    sp.run(command, env=self.env)
AttributeError: 'ExeOOMMFRunner' object has no attribute 'env'
(base) mirocafolla@192 / % python3 -c "import oommfc; oommfc.runner.runner.status"                                         
OOMMFTCL is set, but OOMMF could not be run.
stdout:
b''
stderr:
b'couldn\'t read file "/Users/mirocafolla/.bash_profile/oommf/oommf/oommf.tcl": not a directory\n'
Docker was not found.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mirocafolla/anaconda3/lib/python3.10/site-packages/oommfc/oommf/oommf.py", line 435, in runner
    self.autoselect_runner()
  File "/Users/mirocafolla/anaconda3/lib/python3.10/site-packages/oommfc/oommf/oommf.py", line 572, in autoselect_runner
    raise EnvironmentError("Cannot find OOMMF.")
OSError: Cannot find OOMMF.

**Comment by MiroCaf** [comment]
(base) mirocafolla@192 oommf % python3 -c "import oommfc; oommfc.runner.runner.status"
OOMMFTCL is set, but OOMMF could not be run.
stdout:
b''
stderr:
b'couldn\'t read file "/Users/mirocafolla/.bash_profile/oommf/oommf/oommf.tcl": not a directory\n'
Docker was not found.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mirocafolla/anaconda3/lib/python3.10/site-packages/oommfc/oommf/oommf.py", line 435, in runner
    self.autoselect_runner()
  File "/Users/mirocafolla/anaconda3/lib/python3.10/site-packages/oommfc/oommf/oommf.py", line 572, in autoselect_runner
    raise EnvironmentError("Cannot find OOMMF.")
OSError: Cannot find OOMMF.
(base) mirocafolla@192 oommf %

**Comment by MiroCaf** [comment]
But now python seems to be running okay with just 

import ubermag
import oommfc as oc
import discretisedfield as df

without the need for oommfc.runner.runner = oommfc.oommf.TclOOMMFRunner("/Users/mirocafolla/oommf/oommf/oommf.tcl"

**Comment by DebanjanPolley** [comment]
Recently, I found an easier way to install UBERMAG on a Mac (M1/M2 chip). 

I had to build an osx-64 environment within my M2 Mac in the following way:

1. Create an osx-64 virtual environment, `ubermag_env` 
`CONDA_SUBDIR=osx-64 conda create -n ubermag_env python`
2. activate the virtual environment
`conda activate ubermag_env` 
3. config osx-64
`conda config --env --set subdir osx-64` 

Then use `$ conda install --channel conda-forge ubermag` to install UBERMAG
