### ISSUE TITLE
Issues when installing ubermag- and then I cannot any longer use either Spyder! :(

### ISSUE THREAD

**Issue by MiroCaf** [ubermag/help#276]
Hello, 

I am working on Mac OS Catilina 10.15.7

I installed ubermag following the documentation and using pip. When testing the installation, this does not seem to be working fine.

''' (ubermag_env) stfc-guest-0044:oommf clodomirocafolla$ python3 -c "import oommfc; oommfc.runner.runner.status"
OOMMFTCL is set, but OOMMF could not be run.
stdout:
b''
stderr:
b'couldn\'t read file "Users/clodomirocafolla/oommf/oommf.tcl": no such file or directory\n'
Docker was not found.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/clodomirocafolla/opt/anaconda3/envs/ubermag_env/lib/python3.10/site-packages/oommfc/oommf/oommf.py", line 435, in runner
    self.autoselect_runner()
  File "/Users/clodomirocafolla/opt/anaconda3/envs/ubermag_env/lib/python3.10/site-packages/oommfc/oommf/oommf.py", line 572, in autoselect_runner
    raise EnvironmentError("Cannot find OOMMF.")
OSError: Cannot find OOMMF.
(ubermag_env) stfc-guest-0044:oommf clodomirocafolla$ pwd
/Users/clodomirocafolla/oommf/oommf
(ubermag_env) stfc-guest-0044:oommf clodomirocafolla$ python3 -c "import oommfc; oommfc.runner.runner.status" '''

The main result of trying installing ubermag is that when I try to launch Spyder, this does not seem to be working fine any longer and this error is returned:

''' Traceback (most recent call last):
File "/Users/clodomirocafolla/opt/anaconda3/bin/spyder", line 11, in 
sys.exit(main())
File "/Users/clodomirocafolla/opt/anaconda3/lib/python3.8/site-packages/spyder/app/start.py", line 201, in main
from spyder.app import mainwindow
File "/Users/clodomirocafolla/opt/anaconda3/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 178, in 
from spyder.plugins.help.utils.sphinxify import CSS_PATH, DARK_CSS_PATH
File "/Users/clodomirocafolla/opt/anaconda3/lib/python3.8/site-packages/spyder/plugins/help/utils/sphinxify.py", line 36, in 
from sphinx.application import Sphinx
File "/Users/clodomirocafolla/opt/anaconda3/lib/python3.8/site-packages/sphinx/application.py", line 42, in 
from sphinx.registry import SphinxComponentRegistry
File "/Users/clodomirocafolla/opt/anaconda3/lib/python3.8/site-packages/sphinx/registry.py", line 24, in 
from sphinx.builders import Builder
File "/Users/clodomirocafolla/opt/anaconda3/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 26, in 
from sphinx.util import import_object, logging, rst, progress_message, status_iterator
File "/Users/clodomirocafolla/opt/anaconda3/lib/python3.8/site-packages/sphinx/util/rst.py", line 22, in 
from jinja2 import environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/Users/clodomirocafolla/opt/anaconda3/lib/python3.8/site-packages/jinja2/__init__.py)'''

Any help would be greatly appreciated

**Comment by lang-m** [comment]
Hi @MiroCaf,
please surround code/output with triple backticks (not quotes) as explained here: https://ubermag.github.io/help.html#how-to-prepare-your-request-for-help

Do debug this, we need more information. Could you please run the following commands in a shell with your `ubermag_env` activated:
```
conda list
which spyder
```

and **without** your `ubermag_env` activated:
```
conda list
```

**Comment by MiroCaf** [comment]
Problem solved re-installing anaconda and Ubermag. Thanks though! :)
